<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql"/>
        <PackageReference Include="AspNetCore.HealthChecks.Redis"/>
        <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq"/>
        <PackageReference Include="RabbitMQ.Client"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OrderFlow.Application\OrderFlow.Application.csproj"/>
        <ProjectReference Include="..\OrderFlow.Contracts\OrderFlow.Contracts.csproj"/>
    </ItemGroup>

</Project>
