<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql"/>
        <PackageReference Include="AspNetCore.HealthChecks.Redis"/>
        <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq"/>
        <PackageReference Include="RabbitMQ.Client"/>
        <PackageReference Include="StackExchange.Redis"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="EFCore.NamingConventions"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OrderFlow.Application\OrderFlow.Application.csproj"/>
        <ProjectReference Include="..\OrderFlow.Contracts\OrderFlow.Contracts.csproj"/>
        <ProjectReference Include="..\OrderFlow.Messaging\OrderFlow.Messaging.csproj"/>
    </ItemGroup>

</Project>
